apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-pod
        image: areynolds762/demo-node-website:1.0
        ports:
        -  containerPort: 8080