apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: todo-db-pod
        image: mongo
        ports:
        -  containerPort: 27017
