apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
      - name: todo-web-pod
        image: areynolds762/kubernetes-todo-web
        ports:
        -  containerPort: 8080
