apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-web-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
      - name: todo-web-pod
        image: areynolds762/kubernetes-todo-web:1.0
        ports:
        -  containerPort: 8080