apiVersion: v1
kind: Service
metadata:
  name: todo-web-svc
  labels:
    app: todo-web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: todo-web